# Generated by Django 4.0.1 on 2022-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_servicemodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
