# Generated by Django 4.0.1 on 2022-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_servicemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='service_photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='image',
        ),
    ]
