# Generated by Django 4.0.1 on 2022-01-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_imagemodel_remove_servicemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='service_photos'),
        ),
    ]
