# Generated by Django 4.0.1 on 2022-01-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0008_alter_servicemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='service_photosfaed8f6cee8c4926b8d8710cdc22c6c1.jpg'),
        ),
    ]
