# Generated by Django 4.0.1 on 2022-01-21 07:15

from django.db import migrations, models
import serviceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0009_alter_servicemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(null=True, upload_to=serviceapp.models.path_and_rename),
        ),
    ]
