# Generated by Django 4.0.1 on 2022-01-22 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0011_servicemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
