# Generated by Django 4.0.1 on 2022-01-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceapp', '0014_reviewmodel_remove_servicemodel_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='serviceapp.servicemodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
