# Generated by Django 4.0.1 on 2022-01-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0015_remove_servicemodel_review_reviewmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-date_added']},
        ),
    ]
