# Generated by Django 4.0.1 on 2022-01-25 11:20

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
        ('serviceapp', '0017_alter_servicemodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='address2',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
