# Generated by Django 4.0.1 on 2022-01-25 11:22

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
        ('serviceapp', '0018_servicemodel_address2_alter_servicemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='address2',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
