# Generated by Django 4.0.1 on 2022-01-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0019_alter_servicemodel_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='address2',
        ),
    ]
