# Generated by Django 4.0.1 on 2022-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0020_remove_servicemodel_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
