# Generated by Django 4.0.1 on 2022-01-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0022_address_servicemodel_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='address2',
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='serviceapp.address'),
        ),
    ]
