# Generated by Django 4.0.1 on 2022-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0029_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
