# Generated by Django 4.0.1 on 2022-06-14 09:47

from django.db import migrations, models
import django.db.models.deletion
import serviceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0032_alter_servicemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='serviceapp.servicemodel'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=serviceapp.models.path_and_rename),
        ),
    ]
