# Generated by Django 4.0.1 on 2022-06-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0033_imagemodel_service_alter_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='image',
        ),
    ]
