# Generated by Django 4.0.1 on 2022-06-21 06:28

from django.db import migrations, models
import serviceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0035_alter_imagemodel_image_alter_imagemodel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=serviceapp.models.path_and_rename),
        ),
    ]
